import './globals.css';
import { Geist, Geist_Mono } from 'next/font/google';
import type { Metadata } from 'next';
import { ModalProvider } from '@/app/context/modalcontext';
import Header from '@/app/components/layouts/header';
import Modal from '@/app/components/modal/modal';
import Modaloptions from '@/app/components/modaloptions/modaloptionsignup'
import {IDBooleanProvider}  from '@/app/context/booleancontext';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <IDBooleanProvider>
        <ModalProvider>
          <Header />

          {children}
        </ModalProvider>
        </IDBooleanProvider>
      </body>
    </html>
  );
}
