# Generated by Django 5.2 on 2025-04-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_organization_mogroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='orgCode',
            new_name='orgcode',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='orgName',
            new_name='orgname',
        ),
    ]
