# Generated by Django 5.2 on 2025-05-01 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_organization_orgname_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_sentiment', models.CharField(max_length=50)),
                ('employee_sentiment', models.CharField(max_length=50)),
                ('emotion', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='backend.call')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='backend.user')),
            ],
        ),
    ]
