# Generated by Django 5.2 on 2025-06-06 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='organization',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='backend.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='backend.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mockcallconversation',
            name='organization',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='backend.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mogroup',
            name='session_status',
            field=models.IntegerField(default=0),
        ),
    ]
