# Generated by Django 5.2 on 2025-07-23 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSentimentalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cusanalyses', to='backend.call')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cusanalyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
