# Generated by Django 5.2 on 2025-07-23 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_customersentimentalanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentalanalysis',
            name='customer_sentiment',
        ),
        migrations.AddField(
            model_name='customersentimentalanalysis',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentimentalanalysis',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
